### ISSUE TITLE
Error while whatching

### ISSUE THREAD

**Issue by Shahab-hashemi** [polymorphicshade/Tubular#100] opened 2024-07-08 12:59 UTC
{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=RnYI6Ctai60","content_language":"en-GB","content_country":"GB","app_language":"en_GB","service":"YouTube","package":"org.polymorphicshade.tubular","version":"0.27.0","os":"Linux Android 14 - 34","time":"2024-07-08 14:55","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:103)\n\tat android.os.Looper.loopOnce(Looper.java:232)\n\tat android.os.Looper.loop(Looper.java:317)\n\tat android.os.HandlerThread.run(HandlerThread.java:68)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)\n\tat java.lang.Thread.run(Thread.java:1012)\n"],"user_comment":""}

**Comment by jan-leila** [comment] 2024-07-09 20:35
appears to be a duplicate of https://github.com/polymorphicshade/Tubular/issues/97

**Comment by tuxayo** [comment] 2024-07-10 17:57
This is a duplicate of #97 so close it if possible and copy comments that would bring new info in #97 to there.

**Closed** 2024-07-13 21:00 UTC
Labels: ☹️ ignored issue template
