### ISSUE TITLE
Menu Option not working 

### ISSUE THREAD

**Issue by GreenArchiveForever** [polymorphicshade/Tubular#15] opened 2024-02-02 07:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.r1

### Steps to reproduce the bug

1. open tubular > setting > menu option > choose what to show
2. edit the configuration to your liking
3. save and see the menu isn't working

### Expected behavior

option should working 

### Actual behavior

option isn't working

### Screenshots/Screen recordings

<img alt="Screenshot_20240202-142143" src="https://github.com/polymorphicshade/Tubular/assets/136427398/8f6a88c7-5aff-4372-bec6-0ffca7144725" width=270 />
<img alt="Screenshot_20240202-142135" src="https://github.com/polymorphicshade/Tubular/assets/136427398/cc33c020-64ed-457d-a1dc-09e838ee48a3" width=270 />

### Logs

N/A

### Affected Android/Custom ROM version

A11 RUI 1.0

### Affected device model

RMX2030

### Additional information

.... issues is not exist in official upstream

**Comment by polymorphicshade** [comment] 2024-02-25 23:32
@GreenArchiveForever 
I'm sorry, I don't understand what exactly the problem is. When I edit the tabs, they show up like they should.
Are you trying to customize the drawer menu? I don't know if NewPipe lets you do that.

**Comment by polymorphicshade** [comment] 2024-03-24 22:32
@GreenArchiveForever closing this unless you (or someone else) can explain this issue.

**Closed by polymorphicshade** 2024-03-24 22:32 UTC
Labels: bug

**Comment by GreenArchiveForever** [comment] 2024-03-30 05:24
> @GreenArchiveForever closing this unless you (or someone else) can explain this issue.

hi dev my apologies for took long time to answer after checking official it's looks like human error from my side
turned out that option is not for side menu
