### ISSUE TITLE
Will Tubular be updated to latest NewPipe?

### ISSUE THREAD

**Issue by derei** [polymorphicshade/Tubular#111] opened 2024-07-12 11:25 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

There are A LOT of reports about the latest playback issue ERROR_CODE_IO_BAD_HTTP_STATUS, and Team NewPipe managed to remedy it.

### Expected behavior

https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.1

**Comment by TDavLinguist** [comment] 2024-07-12 12:39
Duplicate of #109

**Comment by sudoshindo** [comment] 2024-07-12 14:09
@derei No
Go away

**Comment by sudoshindo** [comment] 2024-07-12 14:11
@derei 
Fork the code bro
Do it yourself

**Comment by UndeRus** [comment] 2024-07-12 14:53
If you are hurry, you can take temporary fixed build here https://github.com/UndeRus/Tubular/releases/tag/0.27.000 

I will remove it when official build is ready

**Comment by TheBSODAndWSODFan** [comment] 2024-07-12 15:28
@UndeRus also, add [Fix NPE in MediaSessionPlayerUi while destroying player](https://github.com/TeamNewPipe/NewPipe/commit/9f766ebf781b770b6e1b37da084e6193698cee4c) patch

**Comment by UndeRus** [comment] 2024-07-12 16:16
> @UndeRus also, add [Fix NPE in MediaSessionPlayerUi while destroying player](https://github.com/TeamNewPipe/NewPipe/commit/9f766ebf781b770b6e1b37da084e6193698cee4c) patch
> 
> This fix crash in some cases

Take this
https://github.com/UndeRus/Tubular/releases/tag/0.27.0000

**Comment by damrath** [comment] 2024-07-12 18:02
@derei 
> why is there code?!
> just give me the exe

**Comment by jojojojojoj5564656465465** [comment] 2024-07-13 02:38
Pipepipe is already up-to-date

**Comment by TDavLinguist** [comment] 2024-07-13 08:28
> If you are hurry, you can take temporary fixed build here https://github.com/UndeRus/Tubular/releases/tag/0.27.000
> 
> I will remove it when official build is ready

Would you be able to submit a pull request from your repo to this one? That might take come weight off of the dev's shoulders.

**Comment by UndeRus** [comment] 2024-07-13 12:46
> > If you are hurry, you can take temporary fixed build here https://github.com/UndeRus/Tubular/releases/tag/0.27.000
> > I will remove it when official build is ready
> 
> Would you be able to submit a pull request from your repo to this one? That might take some weight off of the dev's shoulders.

I can make this, os I need make these steps:

- fork  https://github.com/polymorphicshade/TubularExtractor, update with upstream NewPipeExtractor and make PR
- When first PR will be finished - fork https://github.com/polymorphicshade/Tubular and update NewPipeExtractor version in project
- Take fixes from original newpipe
- Make PR in tubular

Blocking steps here are PR confirmations from @polymorphicshade 

I can make my steps today(13.07.2024), but bit later, I'm busy right now

**Closed** 2024-07-13 20:56 UTC
Labels: 🪲 bug, ☹️ ignored issue template
