### ISSUE TITLE
Problem when playing videos in the application

### ISSUE THREAD

**Issue by MuerteRoja** [polymorphicshade/Tubular#98] opened 2024-07-06 08:12 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Tubular 0.27.0

### Steps to reproduce the bug

Enter the application
Play a random video
You will be able to see that it suddenly stops, both with the mobile phone screen on or off, in both ways

### Expected behavior

The expected behavior is that videos can be played in the application without any problems

### Actual behavior

The current behavior is that when I play a video in the application with both the mobile phone screen on and off it suddenly stops

## Exception
* _User Action:_ play stream
* _Request:_ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=0caRWqAQFMc
* _Content Country:_ JP
* _Content Language:_ es-
* _App Language:_ es
* _Service:_ YouTube
* _Version:_ 0.27.0
* _OS:_ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

</details>
<hr>

### Affected Android/Custom ROM version

Android 12 / Tubular 0.27.0

### Affected device model

Xiaomi Redmi 9

**Comment by Ao1Pointblank** [comment] 2024-07-08 16:13
Could this be due to sponsor block and the recent YouTube changes involving in-stream ads? 

I will try disabling sponsor block to test.

**Comment by Ao1Pointblank** [comment] 2024-07-09 23:11
> > Could this be due to sponsor block and the recent YouTube changes involving in-stream ads?
> > I will try disabling sponsor block to test.
> 
> Did it work?

Can't test now, there is YT change that broke all the yt-dl(p) based apps which I assume this is. 

Will find out after that issue is resolved.

**Comment by tuxayo** [comment] 2024-07-10 17:58
This is a duplicate of #97 so close it if possible and copy comments that would bring new info in #97 to there.

**Closed** 2024-07-12 18:25 UTC
