### ISSUE TITLE
Tubular crashes when playing video while another one is playing

### ISSUE THREAD

**Issue by hazel-bunny** [polymorphicshade/Tubular#21] opened 2024-02-17 16:24 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1_r2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.Player.setSponsorBlockMode(org.schabi.newpipe.util.SponsorBlockMode)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$onMetadataUpdate$51(VideoDetailFragment.java:1921)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$y7puyGkaa9OmmCWMUbc81ghLLp8(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda56.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
</details>
<hr>

Tried to play https://www.youtube.com/watch?v=aebrG9Q1Im0

**Comment by RoonMoonlight** [comment] 2024-02-19 03:52
Duplicate of #14

**Closed** 2024-02-25 23:43 UTC
