### ISSUE TITLE
Video continuously loads but never plays.

### ISSUE THREAD

**Issue by PhilYellowMilk** [polymorphicshade/Tubular#105] opened 2024-07-11 03:05 UTC
I did want to thank everyone who works on this and spends their time helping us. I really appreciate it, and i know you guys are already working on a new version already. Thank you again.

**Comment by acorreya** [comment] 2024-07-11 08:56
Possible duplicate of #97. I believe this pertains to the changes in YouTube's JS which is being worked on by NewPipe as well as which is superceded in sources at youtube-dl. Youtube-dl seems to almost have a fix ready which has to port to NewPipe and then to Tubular.

**Closed** 2024-07-13 20:58 UTC
Labels: 🪲 bug, ☹️ ignored issue template
